title: Angel Mayta
logo: /assets/img/profile_pic.jpeg
description: Data Scientist con más de 6 años de experiencia en analítica e innovación para riesgo de crédito con foco en Machine Learning, Inteligencia Artificial, Automatización de tareas e Innovación en metodologías de análisis. Tengo experiencia generating value from data by using advanced analytics, setting up big data analytical tools Competencies: Python, Hadoop, Big Data, Hive, SQL, PySpark, Machine Learning, SAS programming, SAS Visual Analytics.
# show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
